#!/bin/sh

set -euo pipefail

DIR="$( cd "$( dirname "$0" )" && pwd )"

# options
ACTION=
RUN_BUILD=
RUN_DESTROY=

MASTERS=${CAASP_NUM_MASTERS:-1}
WORKERS=${CAASP_NUM_WORKERS:-2}
IMAGE=${CAASP_IMAGE:-channel://devel}
PROXY=${CAASP_HTTP_PROXY:-}
PARALLELISM=${CAASP_PARALLELISM:-1}

CAASP_SALT_DIR=${CAASP_SALT_DIR:-$DIR/../../salt}
CAASP_MANIFESTS_DIR=${CAASP_MANIFESTS_DIR:-$DIR/../../caasp-container-manifests}
CAASP_VELUM_DIR=${CAASP_VELUM_DIR:-$DIR/../../velum}

# the environment file
ENVIRONMENT=$DIR/environment.json

USAGE=$(cat <<USAGE
Usage:

  * Building a cluster

    -b|--build             Run the CaaSP KVM Build Step
    -m|--masters <INT>     Number of masters to build (Default: CAASP_NUM_MASTERS=$MASTERS)
    -w|--workers <INT>     Number of workers to build (Default: CAASP_NUM_WORKERS=$WORKERS)
    -i|--image <STR>       Image to use (Default: CAASP_IMAGE=$IMAGE)

  * Destroying a cluster

    -d|--destroy           Run the CaaSP KVM Destroy Step

  * Common options

    -p|--parallelism       Set terraform parallelism (Default: CAASP_PARALLELISM)
    -P|--proxy             Set HTTP proxy (Default: CAASP_HTTP_PROXY)

  * Local git checkouts

     --salt-dir <DIR>      the Salt repo checkout (Default: CAASP_SALT_DIR)
     --manifests-dir <DIR> the manifests repo checkout (Default: CAASP_MANIFESTS_DIR)
     --velum-dir <DIR>     the Velum repo checkout (Default: CAASP_VELUM_DIR)

  * Examples:

  Build a 1 master, 2 worker cluster

  $0 --build -m 1 -w 2

  Build a 1 master, 2 worker cluster using the latest staging A image

  $0 --build -m 1 -w 2 --image channel://staging_a

  Destroy a cluster

  $0 --destroy

USAGE
)

# Utility methods
log()        { (>&2 echo ">>> [caasp-kvm] $@") ; }
warn()       { log "WARNING: $@" ; }
error()      { log "ERROR: $@" ; exit 1 ; }
check_file() { if [ ! -f $1 ]; then error "File $1 doesn't exist!"; fi }
usage()      { echo "$USAGE" ; exit 0 ; }

# parse options
while [[ $# > 0 ]] ; do
  case $1 in
    -b|--build)
      ACTION=1
      RUN_BUILD=1
      ;;
    -m|--masters)
      MASTERS="$2"
      shift
      ;;
    -w|--workers)
      WORKERS="$2"
      shift
      ;;
    -i|--image)
      IMAGE="$2"
      shift
      ;;
    -p|--parallelism)
      PARALLELISM="$2"
      shift
      ;;
    -P|--proxy)
      PROXY="$2"
      shift
      ;;
    -d|--destroy)
      ACTION=1
      RUN_DESTROY=1
      ;;
    --salt-dir)
      CAASP_SALT_DIR="$2"
      shift
      ;;
    --manifests-dir)
      CAASP_MANIFESTS_DIR="$2"
      shift
      ;;
    --velum-dir)
      CAASP_VELUM_DIR="$2"
      shift
      ;;
    -h|--help)
      usage
      ;;
  esac
  shift
done

################################################################

TF_ARGS="-parallelism=$PARALLELISM \
         -var caasp_img_source_url=$IMAGE \
         -var caasp_master_count=$MASTERS \
         -var caasp_worker_count=$WORKERS"

if [ -n "$CAASP_SALT_DIR" ] ; then
  CAASP_SALT_DIR="$(realpath $CAASP_SALT_DIR)"
  TF_ARGS="$TF_ARGS -var kubic_salt_dir=$CAASP_SALT_DIR"
  log "Using Salt dir: $CAASP_SALT_DIR"
fi

if [ -n "$CAASP_VELUM_DIR" ] ; then
  CAASP_VELUM_DIR="$(realpath $CAASP_VELUM_DIR)"
  TF_ARGS="$TF_ARGS -var kubic_velum_dir=$CAASP_VELUM_DIR"
  log "Using Velum dir: $CAASP_VELUM_DIR"
fi

if [ -n "$CAASP_MANIFESTS_DIR" ] ; then
  CAASP_MANIFESTS_DIR="$(realpath $CAASP_MANIFESTS_DIR)"
  TF_ARGS="$TF_ARGS -var kubic_caasp_container_manifests_dir=$CAASP_MANIFESTS_DIR"
  log "Using Manifests dir: $CAASP_MANIFESTS_DIR"
fi

# Core methods
build() {
  log "CaaS Platform Building"

  log "Downloading CaaSP KVM Image"
  $DIR/../misc-tools/download-image --proxy "${PROXY}" --type kvm $IMAGE

  if [ -n "$CAASP_VELUM_DIR" ] ; then
    log "Building Velum Development Image"
    $DIR/tools/build-velum-image "$CAASP_VELUM_DIR" "${PROXY}"

    log "Creating Velum Directories"
    mkdir -p "$CAASP_VELUM_DIR/tmp" "$CAASP_VELUM_DIR/log" "$CAASP_VELUM_DIR/vendor/bundle"

    log "Copying CaaSP Container Manifests"
    local injected="$(realpath injected-caasp-container-manifests)"
    rm -rf $injected/*
    cp -r $CAASP_MANIFESTS_DIR/* "$injected/"

    log "Patching Container Manifests"
    $DIR/tools/fix-kubelet-manifest -o $injected/public.yaml $injected/public.yaml
  else
    log "Skipping Velum environment"
  fi

  log "Applying terraform configuration"
  terraform apply $TF_ARGS

  $DIR/tools/generate-environment
  $DIR/../misc-tools/generate-ssh-config $ENVIRONMENT

  log "Waiting for Velum to start - this may take a while"
  PYTHONUNBUFFERED=1 "$DIR/../misc-tools/wait-for-velum" https://$(jq -r '.dashboardHost' "$ENVIRONMENT")

  log "CaaS Platform Ready for bootstrap"
}

destroy() {
  log "Destroying terraform configuration"
  terraform destroy -force $TF_ARGS && \
    rm -f "$ENVIRONMENT"
}

[ -n "$ACTION"      ] || usage
[ -n "$RUN_BUILD"   ] && build
[ -n "$RUN_DESTROY" ] && destroy

exit 0

