source "https://rubygems.org"

gem "capybara"
gem "poltergeist"
gem "rspec"
gem "rspec_junit_formatter"

# make sure rack doesn't require ruby >= 2.2.2
# # as we have ruby 2.1 on SLE12
gem "rack", "~> 1.6.5"

gem "pry"
gem "pry-nav"

group :travis_ci do
  gem "rubocop"
  gem "rubocop-rspec"
end
