#!/usr/bin/env python

"""
    Runs end-to-end product tests.
    This script can be run from Jenkins or manually, on developer desktops or servers.
"""

# TODO
#   create venv
#   discover pytest tests
#   report xml output

from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import subprocess
import logging
import os
import sys

log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)

__version__ = "0.0.1"

def main():
    print("Testrunner v. {}".format(__version__))


if __name__ == '__main__':
    main()
