#!/bin/bash

type python3 >/dev/null 2>&1 || sudo zypper install --no-confirm python3

if [ ! -d ~/py3venv ]; then
  python3 -m venv ~/py3venv
fi
~/py3venv/bin/pip3 install requests pygal
~/py3venv/bin/python3 $(dirname $0)/capture.py $@
